#!/usr/local/bin/tclsh8.4
# Sets up configuration stuff
# $Amigan: phoned/configure.tcl,v 1.1 2005/06/27 20:47:37 dcp1990 Exp $
if {$argc < 1} {
	puts stderr "Usage: configure.tcl prefix"
	exit -1
}
set prefix [lindex $argv 0]
puts [list Prefix is [set prefix]...]
puts Configuring.
set xf [open "xfone/paths.tcl" w]
puts $xf {# Generated by configure.tcl}
puts $xf [list set prefix $prefix]
puts $xf {set lib [set prefix]/lib/phoned
set udom_lib [set lib]/udom.so
}
close $xf
#for lack of touch...
close [open .config w]

