#!/usr/local/bin/tclsh8.4
# Sets up configuration stuff
# $Amigan: phoned/configure.tcl,v 1.2 2005/06/27 21:05:51 dcp1990 Exp $
if {$argc < 2} {
	puts stderr "Usage: configure.tcl prefix testing"
	exit -1
}
set prefix [lindex $argv 0]
set testing [lindex $argv 1]
puts [list Prefix is [set prefix]...]
puts Configuring.
set xf [open "xfone/paths.tcl" w]
if {!$testing} {
	puts $xf {# Generated by configure.tcl}
	puts $xf [list set prefix $prefix]
	puts $xf {set lib [set prefix]/lib/phoned
set udom_lib [set lib]/udom.so
}
} else {
	puts $xf {# TESTING...generated by configure.tcl}
	puts $xf [list set pfx [pwd]]
	puts $xf {set lib [set pfx]/lib/tcl
set udom_lib [set lib]/udom.so
}
}
close $xf
#for lack of touch...
close [open .config w]

