# cnd Makefile
# (C)2005, Dan Ponte
# $Amigan: phoned/phonectl/Makefile,v 1.2 2005/06/01 00:43:07 dcp1990 Exp $
include ../global.mk
# basic stuff. we append for a reason.
CPPFLAGS=-I../include
CFLAGS+=-g -Wall -W -ansi ${CPPFLAGS}
LDFLAGS=
# keep these up to date.
MAINBIN=phonectl
SRCS=phonectl.c
OBJS=phonectl.o
include ../main.mk
