# cnd Makefile
# (C)2005, Dan Ponte
# $Amigan: phoned/scripts/Makefile,v 1.1 2005/06/19 05:50:23 dcp1990 Exp $
include ../global.mk
# basic stuff. we append for a reason.
CPPFLAGS+=-I/usr/local/include/tcl8.4
CFLAGS+=-g ${CPPFLAGS}
LDFLAGS+=-shared
# keep these up to date.
MAINBIN=terminal.so
SRCS=terminal.c
OBJS=terminal.o

include ../main.mk
ourclean:

