# cnd Makefile
# (C)2005, Dan Ponte
include ../global.mk
# basic stuff. we append for a reason.
CPPFLAGS+=-I../include
CFLAGS+=-g -Wall -W -ansi ${CPPFLAGS}
LDFLAGS+=
# keep these up to date.
MAINBIN=cnd
SRCS=cnd.c
OBJS=cnd.o
include ../main.mk
