# cnd Makefile
# $Amigan: phoned/cnd/Makefile,v 1.2 2005/06/01 00:43:07 dcp1990 Exp $
# (C)2005, Dan Ponte
include ../global.mk
# basic stuff. we append for a reason.
CPPFLAGS=-I../include
CFLAGS+=-g -Wall -W -ansi ${CPPFLAGS}
LDFLAGS=
# keep these up to date.
MAINBIN=cnd
SRCS=cnd.c
OBJS=cnd.o
include ../main.mk
