# cnd Makefile
# (C)2005, Dan Ponte
# $Amigan: phoned/xfone/Makefile,v 1.3 2005/06/27 21:05:52 dcp1990 Exp $
include ../global.mk
# basic stuff. we append for a reason.
all:

clean:
	rm -f paths.tcl *.core *~
